spring:
  datasource:
    url: jdbc:mysql://localhost:3306/time_rocket_db?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: root
  jackson:
    time-zone: Asia/Seoul

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.my.community.domain
  configuration:
    map-underscore-to-camel-case: true
